---
title: "Sample Likert Data Generation"
author: "Jake Chanenson"
date: "6/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Dental Hygine Data Set}
## Generate random distro for each question
mouth_wash <- c(rep("Never", 26), rep("Rarely", 10), rep("Sometimes", 9), rep("Often", 37), rep("Always", 18))

tooth_brush <- c(rep("Never", 19), rep("Rarely", 24), rep("Sometimes", 18), rep("Often", 11), rep("Always", 28))

floss <- c(rep("Never", 36), rep("Rarely", 26), rep("Sometimes", 6), rep("Often", 22), rep("Always", 10))

age <- rep(c(rep("Child", 7), rep("Teen", 8), rep("Adult", 1)), length.out = 100)

## Fix factor levels
floss <- factor(floss, c("Never", "Rarely", "Sometimes", "Often", "Always"))
age <- factor(age, c("Child", "Teen", "Adult"))

## Create Data Set
dental_hyg <- data.frame(mouth_wash, tooth_brush, floss, age)

## Rename Cols
dental_hyg  <- dental_hyg  %>% 
  rename("How Often Respondents Use Mouth Wash" = mouth_wash,
          "How Often Respondents Brush Their Teeth" = tooth_brush,
          "How Often Respondents Use Floss" = floss)
head(dental_hyg)
```

```{r Cookie-Type}
## Create df
Item <- c("Oatmeal Raisin is The Best Type of Cookie", "Chocolate Chip is The Best Type of Cookie", "Snickerdoodle is The Best Type of Cookie")
strong_disagree <- c(60, 20, 10)
disagree <- c(7, 25, 47)
neutral <- c(0,0,0)
agree <- c(3, 15, 38)
strong_agree  <- c(30, 40, 05)
cookie_data <- data.frame(Item, strong_disagree, disagree, neutral, agree, strong_agree)

## Rename Cols (for legend)
cookie_data <- cookie_data  %>% 
  rename("Strong Disagree" = strong_disagree,
          "Disagree" = disagree,
          "Agree" = agree,
         "Strong Agree" = strong_agree)
head(cookie_data)
```

```{r}
save(dental_hyg, cookie_data, file = "../data/sample-likert-data.rda")
```

